version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: spatie-pdf-app
    container_name: spatie-pdf-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_KEY=
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=ashan
      - DB_PASSWORD=
