<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Generated PDF {{ $id }}</title>
    <style>
        body {
            font-family: 'Helvetica', Arial, sans-serif;
            margin: 40px;
            line-height: 1.6;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 1px solid #eee;
        }
        .header h1 {
            color: #2563eb;
            font-size: 28px;
            margin-bottom: 5px;
        }
        .content {
            margin-top: 30px;
        }
        .info-box {
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 5px;
            padding: 20px;
            margin: 20px 0;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 12px;
            color: #6b7280;
            padding-top: 20px;
            border-top: 1px solid #eee;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>API Generated Document</h1>
        <p>Document generated through API endpoint</p>
    </div>
    
    <div class="content">
        <div class="info-box">
            <h2>Document Information</h2>
            <p><strong>Document ID:</strong> {{ $id }}</p>
            <p><strong>Generated at:</strong> {{ now()->format('Y-m-d H:i:s') }}</p>
            <p><strong>Generated by:</strong> Spatie PDF API</p>
        </div>
        
        <p>This document was automatically generated using the Laravel Spatie PDF package.</p>
        <p>The unique identifier <strong>{{ $id }}</strong> was provided through the API endpoint.</p>
    </div>
    
    <div class="footer">
        <p>© {{ date('Y') }} Laravel Spatie PDF Application</p>
    </div>
</body>
</html>
